### ISSUE TITLE
Tag armv6 not found in repository docker.io/alexellis2/node4.x-arm

### ISSUE THREAD

**Issue by Niffler** [alexellis/ghost-on-docker#1]
I tried to build my own image from your Dockerfile (ARMv6) for a Raspberry Pi Model B, but it did not work, because the docker repository tag **armv6** is not available. The two available repository tags are **v6** and **latest**.

**Comment by alexellis** [comment]
You closed the issue immediately?

There is a new version of ghost I'm pushing through alexellis2/ghost-armv6:10.0.1

**Comment by Niffler** [comment]
Yes , the updated Dockerfile (ARMv6) no longer uses "alexellis2/node4.x-arm".
Thanks, but I built my own image from a Dockerfile that is based on your Dockerfile.
