### ISSUE TITLE
What is sed in your Dockerfile?

### ISSUE THREAD

**Issue by Vadorequest** [alexellis/ghost-on-docker#11]
Hello, I'm trying to understand what you did in your Dockerfile but I don't find any reference for the `sed` command.

`RUN sed -i s/my-ghost-blog.com/blog.alexellis.io/g config.js`

I assume it's a third party software?

**Comment by johnmccabe** [comment]
Hey @Vadorequest, `sed` is a linux utility for making changes to text - https://www.gnu.org/software/sed/manual/sed.html#Introduction

In this `RUN` line its editing the `config.js` file, searching (`s/`) for the text `my-ghost-blog.com` and when it encounters it change it to `blog.alexellis.io` - and its doing it for every occurrence in the file (`/g`).

100% recommend reading up on `sed`, its amazingly useful.

**Comment by johnmccabe** [comment]
Derek add label: question

**Comment by Vadorequest** [comment]
@alexellis Thanks for your blog about Ghost and Docker. It took me a while to figure out how to put all the pieces together, but I've got a good setup, very light, and super easy to install on any VPS.
https://github.com/Vadorequest/eclats-de-voix

Thanks again!
