### ISSUE TITLE
Update to Ghost 0.11.1

### ISSUE THREAD

**Issue by hermanzdosilovic** [alexellis/ghost-on-docker#2]

**Comment by alexellis** [comment]
I'm working on this at the moment - maybe next week I'll be able to push it.. 

Which one do you need - ARM or regular PC?

**Comment by hermanzdosilovic** [comment]
Hi, sorry for the delay. I need ARMv7.

**Comment by neotic82** [comment]
Hi @hermanzdosilovic ! 

I just completed the update following these steps and everything perfect with the latest version in armv7 dockerfile  :+1: 

http://support.ghost.org/how-to-upgrade/

I hope to help you ;)

![update_ghost](https://cloud.githubusercontent.com/assets/7745739/22296987/331eb750-e31c-11e6-959a-9f91de912646.jpg)

P.D Thanks @alexellis for this images :)

**Comment by hermanzdosilovic** [comment]
Thanks @neotic82. I have actually created PR #3 for this which @alexellis merged. According to [last updated time](https://hub.docker.com/r/alexellis2/ghost-on-docker/tags/) for `armv7` tag, I don't think @alexellis pushed this new version to Docker Hub. But you can find this new version in my repo `hermanzdosilovic/ghost:armv7`.

**Comment by alexellis** [comment]
I am looking at moving to Alpine Linux for the Ghost images because it's much smaller, but was running into issues with compiling SQLite

**Comment by alexellis** [comment]
I am not sure about continuing support for armv6.. what about you guys?

**Comment by neotic82** [comment]
Hi! @alexellis 

The change to alpine would be great, the image is too heavy. 
I am currently testing it and weighing 884 mb without having anything published in ghost. 
Alpine combined with ghost would be monumental :) 

Support for arm6 will already depend on the number of pulls people make of that container ;)

**Comment by alexellis** [comment]
@neotic82 I'm not convinced that you can break down pull count by tag, only by repo - which is over here: https://hub.docker.com/r/alexellis2/ghost-on-docker/tags/

Pull count for all tags is just under 800. https://registry.hub.docker.com/v2/repositories/alexellis2/ghost-on-docker/

ARMv6 (Pi Zero and original Pi) give such poor performance it's not really worth anyone's time to run Ghost there. ARMv7 = Pi 2 / 3.

The main problem with Alpine is that a whole build-toolchain is required to compile SQLite - probably also needs GLibC. Here's were I got with it if you want to continue:

https://gist.github.com/alexellis/bc668876815bbc0cf1428c7aa37e5e46

**Comment by neotic82** [comment]
Hi @alexellis !

> docker pull alexellis2/ghost-on-docker:armv7
> docker images
> alexellis2/ghost-on-docker   armv7   ba9e25b6aa98   9 months ago   **884.8 MB**

The images to docker hub are uploaded compressed, I was talking about the decompressed weight. Just the arm7 has a size greater than 800 mb jejeje

That's why I told you that if it were with alpine, it would be much lighter. 
I'll check the dockerfile to see if it can solve the sqlite issue.

Thnks!

:P

**Comment by alexellis** [comment]
I meant 800 pulls, not 800MB, sorry.

We should care about making this a smaller image. Ideally we want the upstream SQLite-node project to provide an armv7 binary for when people do an `npm install sqlite`. There is an open issue but they don't seem to be making any movement with it. 

https://github.com/mapbox/node-sqlite3/issues/597
