### ISSUE TITLE
Update ARMv6 image on Hub

### ISSUE THREAD

**Issue by alexellis** [alexellis/ghost-on-docker#5]
Update ARMv6 image for @jmkhael

**Comment by alexellis** [comment]
Hey @jmkhael - please try out your new Docker image which I tested this morning -> alexellis2/ghost-on-docker:armv6-0.11.8

(Just started pushing it to the hub)

**Comment by jmkhael** [comment]
Hello @alexellis, thank you. I'm pulling the new image. I'll let you know once it finishes extracting
