### ISSUE TITLE
armv7 image is outdated

### ISSUE THREAD

**Issue by aaronkjones** [alexellis/ghost-on-docker#6]
Spinning up the armv7 image and proceeding to the admin section produces "Ghost 0.11.8 is available! Hot Damn. Click here to upgrade."

**Comment by alexellis** [comment]
Ghost have a fast release cycle, so I would expect this not to be tracking the cutting edge releases.

You can do a couple of things:

* Look at the tags available on [Docker Hub](https://hub.docker.com/r/alexellis2/ghost-on-docker/tags/) and see if there is a newer image
* Build your own image using the detailed instructions

* Ask me to spend a couple of hours of my own time creating an updated image for you

**Comment by aaronkjones** [comment]
Thank you for the clarification. I did not realize Ghost has such a fast release cycle. I gave a star for your work on this :+1:

**Comment by alexellis** [comment]
I've pushed a new version but today 0.11.19 came out!

**Comment by aaronkjones** [comment]
Your new nickname: Sisyphus :rofl:
