### ISSUE TITLE
Using Data Volumes

### ISSUE THREAD

**Issue by ghost** [alexellis/ghost-on-docker#7]
Which directory would we want to map a data volume to if we want to persist our data outside of the container, but still be able to easily update the container when new versions are released?

**Comment by ghost** [comment]
I see this is now in the "Coming Soon" section. Closing issue.

**Comment by alexellis** [comment]
/var/www/ghost I'd say is your best bet. Check out the blog - keep shipping your blog with Docker Volumes. https://blog.alexellis.io/tag/blog/
